// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/env.proto

package bot.cline.host.proto;

public final class Env {
  private Env() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_host_GetHostVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_host_GetHostVersionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_host_GetTelemetrySettingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_host_GetTelemetrySettingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_host_TelemetrySettingsEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_host_TelemetrySettingsEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016host/env.proto\022\004host\032\022cline/common.pro" +
      "to\"\264\001\n\026GetHostVersionResponse\022\025\n\010platfor" +
      "m\030\001 \001(\tH\000\210\001\001\022\024\n\007version\030\002 \001(\tH\001\210\001\001\022\027\n\ncl" +
      "ine_type\030\003 \001(\tH\002\210\001\001\022\032\n\rcline_version\030\004 \001" +
      "(\tH\003\210\001\001B\013\n\t_platformB\n\n\010_versionB\r\n\013_cli" +
      "ne_typeB\020\n\016_cline_version\"A\n\034GetTelemetr" +
      "ySettingsResponse\022!\n\nis_enabled\030\001 \001(\0162\r." +
      "host.Setting\";\n\026TelemetrySettingsEvent\022!" +
      "\n\nis_enabled\030\001 \001(\0162\r.host.Setting*5\n\007Set" +
      "ting\022\017\n\013UNSUPPORTED\020\000\022\013\n\007ENABLED\020\001\022\014\n\010DI" +
      "SABLED\020\0022\322\003\n\nEnvService\0228\n\022clipboardWrit" +
      "eText\022\024.cline.StringRequest\032\014.cline.Empt" +
      "y\0227\n\021clipboardReadText\022\023.cline.EmptyRequ" +
      "est\032\r.cline.String\022C\n\016getHostVersion\022\023.c" +
      "line.EmptyRequest\032\034.host.GetHostVersionR" +
      "esponse\0227\n\021getIdeRedirectUri\022\023.cline.Emp" +
      "tyRequest\032\r.cline.String\022O\n\024getTelemetry" +
      "Settings\022\023.cline.EmptyRequest\032\".host.Get" +
      "TelemetrySettingsResponse\022S\n\034subscribeTo" +
      "TelemetrySettings\022\023.cline.EmptyRequest\032\034" +
      ".host.TelemetrySettingsEvent0\001\022-\n\010shutdo" +
      "wn\022\023.cline.EmptyRequest\032\014.cline.EmptyB7\n" +
      "\024bot.cline.host.protoP\001Z\035github.com/clin" +
      "e/grpc-go/hostb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          bot.cline.proto.Common.getDescriptor(),
        });
    internal_static_host_GetHostVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_host_GetHostVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_host_GetHostVersionResponse_descriptor,
        new java.lang.String[] { "Platform", "Version", "ClineType", "ClineVersion", "Platform", "Version", "ClineType", "ClineVersion", });
    internal_static_host_GetTelemetrySettingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_host_GetTelemetrySettingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_host_GetTelemetrySettingsResponse_descriptor,
        new java.lang.String[] { "IsEnabled", });
    internal_static_host_TelemetrySettingsEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_host_TelemetrySettingsEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_host_TelemetrySettingsEvent_descriptor,
        new java.lang.String[] { "IsEnabled", });
    bot.cline.proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
