// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface ExecuteCommandInTerminalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ExecuteCommandInTerminalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The command to execute
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <pre>
   * The command to execute
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
