// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface ExecuteCommandInTerminalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ExecuteCommandInTerminalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether the command was successfully sent to the terminal
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
