// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface GetActiveEditorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetActiveEditorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string file_path = 1;</code>
   * @return Whether the filePath field is set.
   */
  boolean hasFilePath();
  /**
   * <code>optional string file_path = 1;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>optional string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
