// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface GetDiagnosticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetDiagnosticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  bot.cline.proto.Metadata getMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   */
  bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder();
}
