// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

public interface GetDocumentTextResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetDocumentTextResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string content = 1;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
