// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface GetDiagnosticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetDiagnosticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cline.FileDiagnostics file_diagnostics = 1;</code>
   */
  java.util.List<bot.cline.proto.FileDiagnostics> 
      getFileDiagnosticsList();
  /**
   * <code>repeated .cline.FileDiagnostics file_diagnostics = 1;</code>
   */
  bot.cline.proto.FileDiagnostics getFileDiagnostics(int index);
  /**
   * <code>repeated .cline.FileDiagnostics file_diagnostics = 1;</code>
   */
  int getFileDiagnosticsCount();
  /**
   * <code>repeated .cline.FileDiagnostics file_diagnostics = 1;</code>
   */
  java.util.List<? extends bot.cline.proto.FileDiagnosticsOrBuilder> 
      getFileDiagnosticsOrBuilderList();
  /**
   * <code>repeated .cline.FileDiagnostics file_diagnostics = 1;</code>
   */
  bot.cline.proto.FileDiagnosticsOrBuilder getFileDiagnosticsOrBuilder(
      int index);
}
