// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/env.proto

package bot.cline.host.proto;

/**
 * Protobuf type {@code host.GetTelemetrySettingsResponse}
 */
public final class GetTelemetrySettingsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.GetTelemetrySettingsResponse)
    GetTelemetrySettingsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTelemetrySettingsResponse.newBuilder() to construct.
  private GetTelemetrySettingsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTelemetrySettingsResponse() {
    isEnabled_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTelemetrySettingsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTelemetrySettingsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            isEnabled_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Env.internal_static_host_GetTelemetrySettingsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Env.internal_static_host_GetTelemetrySettingsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.GetTelemetrySettingsResponse.class, bot.cline.host.proto.GetTelemetrySettingsResponse.Builder.class);
  }

  public static final int IS_ENABLED_FIELD_NUMBER = 1;
  private int isEnabled_;
  /**
   * <code>.host.Setting is_enabled = 1;</code>
   * @return The enum numeric value on the wire for isEnabled.
   */
  @java.lang.Override public int getIsEnabledValue() {
    return isEnabled_;
  }
  /**
   * <code>.host.Setting is_enabled = 1;</code>
   * @return The isEnabled.
   */
  @java.lang.Override public bot.cline.host.proto.Setting getIsEnabled() {
    @SuppressWarnings("deprecation")
    bot.cline.host.proto.Setting result = bot.cline.host.proto.Setting.valueOf(isEnabled_);
    return result == null ? bot.cline.host.proto.Setting.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isEnabled_ != bot.cline.host.proto.Setting.UNSUPPORTED.getNumber()) {
      output.writeEnum(1, isEnabled_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isEnabled_ != bot.cline.host.proto.Setting.UNSUPPORTED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, isEnabled_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.GetTelemetrySettingsResponse)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.GetTelemetrySettingsResponse other = (bot.cline.host.proto.GetTelemetrySettingsResponse) obj;

    if (isEnabled_ != other.isEnabled_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + isEnabled_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.GetTelemetrySettingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.GetTelemetrySettingsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code host.GetTelemetrySettingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.GetTelemetrySettingsResponse)
      bot.cline.host.proto.GetTelemetrySettingsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Env.internal_static_host_GetTelemetrySettingsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Env.internal_static_host_GetTelemetrySettingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.GetTelemetrySettingsResponse.class, bot.cline.host.proto.GetTelemetrySettingsResponse.Builder.class);
    }

    // Construct using bot.cline.host.proto.GetTelemetrySettingsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isEnabled_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Env.internal_static_host_GetTelemetrySettingsResponse_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.GetTelemetrySettingsResponse getDefaultInstanceForType() {
      return bot.cline.host.proto.GetTelemetrySettingsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.GetTelemetrySettingsResponse build() {
      bot.cline.host.proto.GetTelemetrySettingsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.GetTelemetrySettingsResponse buildPartial() {
      bot.cline.host.proto.GetTelemetrySettingsResponse result = new bot.cline.host.proto.GetTelemetrySettingsResponse(this);
      result.isEnabled_ = isEnabled_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.GetTelemetrySettingsResponse) {
        return mergeFrom((bot.cline.host.proto.GetTelemetrySettingsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.GetTelemetrySettingsResponse other) {
      if (other == bot.cline.host.proto.GetTelemetrySettingsResponse.getDefaultInstance()) return this;
      if (other.isEnabled_ != 0) {
        setIsEnabledValue(other.getIsEnabledValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.GetTelemetrySettingsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.GetTelemetrySettingsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int isEnabled_ = 0;
    /**
     * <code>.host.Setting is_enabled = 1;</code>
     * @return The enum numeric value on the wire for isEnabled.
     */
    @java.lang.Override public int getIsEnabledValue() {
      return isEnabled_;
    }
    /**
     * <code>.host.Setting is_enabled = 1;</code>
     * @param value The enum numeric value on the wire for isEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnabledValue(int value) {
      
      isEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.host.Setting is_enabled = 1;</code>
     * @return The isEnabled.
     */
    @java.lang.Override
    public bot.cline.host.proto.Setting getIsEnabled() {
      @SuppressWarnings("deprecation")
      bot.cline.host.proto.Setting result = bot.cline.host.proto.Setting.valueOf(isEnabled_);
      return result == null ? bot.cline.host.proto.Setting.UNRECOGNIZED : result;
    }
    /**
     * <code>.host.Setting is_enabled = 1;</code>
     * @param value The isEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnabled(bot.cline.host.proto.Setting value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      isEnabled_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.host.Setting is_enabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEnabled() {
      
      isEnabled_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.GetTelemetrySettingsResponse)
  }

  // @@protoc_insertion_point(class_scope:host.GetTelemetrySettingsResponse)
  private static final bot.cline.host.proto.GetTelemetrySettingsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.GetTelemetrySettingsResponse();
  }

  public static bot.cline.host.proto.GetTelemetrySettingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTelemetrySettingsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTelemetrySettingsResponse>() {
    @java.lang.Override
    public GetTelemetrySettingsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTelemetrySettingsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTelemetrySettingsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTelemetrySettingsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.GetTelemetrySettingsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

