// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface GetVisibleTabsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetVisibleTabsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string paths = 1;</code>
   * @return A list containing the paths.
   */
  java.util.List<java.lang.String>
      getPathsList();
  /**
   * <code>repeated string paths = 1;</code>
   * @return The count of paths.
   */
  int getPathsCount();
  /**
   * <code>repeated string paths = 1;</code>
   * @param index The index of the element to return.
   * @return The paths at the given index.
   */
  java.lang.String getPaths(int index);
  /**
   * <code>repeated string paths = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the paths at the given index.
   */
  com.google.protobuf.ByteString
      getPathsBytes(int index);
}
