// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface GetWorkspacePathsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.GetWorkspacePathsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique ID for the workspace/project.
   * This is currently optional in vscode. It is required in other environments where cline is running at
   * the application level, and the user can open multiple projects.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * The unique ID for the workspace/project.
   * This is currently optional in vscode. It is required in other environments where cline is running at
   * the application level, and the user can open multiple projects.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The unique ID for the workspace/project.
   * This is currently optional in vscode. It is required in other environments where cline is running at
   * the application level, and the user can open multiple projects.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
