// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface OpenFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.OpenFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
