// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

public interface OpenDiffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.OpenDiffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  bot.cline.proto.Metadata getMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   */
  bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * The absolute path of the document being edited.
   * </pre>
   *
   * <code>optional string path = 2;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <pre>
   * The absolute path of the document being edited.
   * </pre>
   *
   * <code>optional string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <pre>
   * The absolute path of the document being edited.
   * </pre>
   *
   * <code>optional string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * The new content for the file.
   * </pre>
   *
   * <code>optional string content = 3;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <pre>
   * The new content for the file.
   * </pre>
   *
   * <code>optional string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * The new content for the file.
   * </pre>
   *
   * <code>optional string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
