// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

public interface OpenClineSidebarPanelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.OpenClineSidebarPanelRequest)
    com.google.protobuf.MessageOrBuilder {
}
