// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

/**
 * Protobuf type {@code host.OpenMultiFileDiffRequest}
 */
public final class OpenMultiFileDiffRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.OpenMultiFileDiffRequest)
    OpenMultiFileDiffRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OpenMultiFileDiffRequest.newBuilder() to construct.
  private OpenMultiFileDiffRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OpenMultiFileDiffRequest() {
    title_ = "";
    diffs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OpenMultiFileDiffRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OpenMultiFileDiffRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            title_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              diffs_ = new java.util.ArrayList<bot.cline.host.proto.ContentDiff>();
              mutable_bitField0_ |= 0x00000002;
            }
            diffs_.add(
                input.readMessage(bot.cline.host.proto.ContentDiff.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        diffs_ = java.util.Collections.unmodifiableList(diffs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Diff.internal_static_host_OpenMultiFileDiffRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Diff.internal_static_host_OpenMultiFileDiffRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.OpenMultiFileDiffRequest.class, bot.cline.host.proto.OpenMultiFileDiffRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object title_;
  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  @java.lang.Override
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIFFS_FIELD_NUMBER = 2;
  private java.util.List<bot.cline.host.proto.ContentDiff> diffs_;
  /**
   * <code>repeated .host.ContentDiff diffs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<bot.cline.host.proto.ContentDiff> getDiffsList() {
    return diffs_;
  }
  /**
   * <code>repeated .host.ContentDiff diffs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends bot.cline.host.proto.ContentDiffOrBuilder> 
      getDiffsOrBuilderList() {
    return diffs_;
  }
  /**
   * <code>repeated .host.ContentDiff diffs = 2;</code>
   */
  @java.lang.Override
  public int getDiffsCount() {
    return diffs_.size();
  }
  /**
   * <code>repeated .host.ContentDiff diffs = 2;</code>
   */
  @java.lang.Override
  public bot.cline.host.proto.ContentDiff getDiffs(int index) {
    return diffs_.get(index);
  }
  /**
   * <code>repeated .host.ContentDiff diffs = 2;</code>
   */
  @java.lang.Override
  public bot.cline.host.proto.ContentDiffOrBuilder getDiffsOrBuilder(
      int index) {
    return diffs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    for (int i = 0; i < diffs_.size(); i++) {
      output.writeMessage(2, diffs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    for (int i = 0; i < diffs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, diffs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.OpenMultiFileDiffRequest)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.OpenMultiFileDiffRequest other = (bot.cline.host.proto.OpenMultiFileDiffRequest) obj;

    if (hasTitle() != other.hasTitle()) return false;
    if (hasTitle()) {
      if (!getTitle()
          .equals(other.getTitle())) return false;
    }
    if (!getDiffsList()
        .equals(other.getDiffsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTitle()) {
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
    }
    if (getDiffsCount() > 0) {
      hash = (37 * hash) + DIFFS_FIELD_NUMBER;
      hash = (53 * hash) + getDiffsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.OpenMultiFileDiffRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.OpenMultiFileDiffRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code host.OpenMultiFileDiffRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.OpenMultiFileDiffRequest)
      bot.cline.host.proto.OpenMultiFileDiffRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Diff.internal_static_host_OpenMultiFileDiffRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Diff.internal_static_host_OpenMultiFileDiffRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.OpenMultiFileDiffRequest.class, bot.cline.host.proto.OpenMultiFileDiffRequest.Builder.class);
    }

    // Construct using bot.cline.host.proto.OpenMultiFileDiffRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDiffsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      title_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (diffsBuilder_ == null) {
        diffs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        diffsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Diff.internal_static_host_OpenMultiFileDiffRequest_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.OpenMultiFileDiffRequest getDefaultInstanceForType() {
      return bot.cline.host.proto.OpenMultiFileDiffRequest.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.OpenMultiFileDiffRequest build() {
      bot.cline.host.proto.OpenMultiFileDiffRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.OpenMultiFileDiffRequest buildPartial() {
      bot.cline.host.proto.OpenMultiFileDiffRequest result = new bot.cline.host.proto.OpenMultiFileDiffRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.title_ = title_;
      if (diffsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          diffs_ = java.util.Collections.unmodifiableList(diffs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.diffs_ = diffs_;
      } else {
        result.diffs_ = diffsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.OpenMultiFileDiffRequest) {
        return mergeFrom((bot.cline.host.proto.OpenMultiFileDiffRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.OpenMultiFileDiffRequest other) {
      if (other == bot.cline.host.proto.OpenMultiFileDiffRequest.getDefaultInstance()) return this;
      if (other.hasTitle()) {
        bitField0_ |= 0x00000001;
        title_ = other.title_;
        onChanged();
      }
      if (diffsBuilder_ == null) {
        if (!other.diffs_.isEmpty()) {
          if (diffs_.isEmpty()) {
            diffs_ = other.diffs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDiffsIsMutable();
            diffs_.addAll(other.diffs_);
          }
          onChanged();
        }
      } else {
        if (!other.diffs_.isEmpty()) {
          if (diffsBuilder_.isEmpty()) {
            diffsBuilder_.dispose();
            diffsBuilder_ = null;
            diffs_ = other.diffs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            diffsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDiffsFieldBuilder() : null;
          } else {
            diffsBuilder_.addAllMessages(other.diffs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.OpenMultiFileDiffRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.OpenMultiFileDiffRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>optional string title = 1;</code>
     * @return Whether the title field is set.
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      bitField0_ = (bitField0_ & ~0x00000001);
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      title_ = value;
      onChanged();
      return this;
    }

    private java.util.List<bot.cline.host.proto.ContentDiff> diffs_ =
      java.util.Collections.emptyList();
    private void ensureDiffsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        diffs_ = new java.util.ArrayList<bot.cline.host.proto.ContentDiff>(diffs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bot.cline.host.proto.ContentDiff, bot.cline.host.proto.ContentDiff.Builder, bot.cline.host.proto.ContentDiffOrBuilder> diffsBuilder_;

    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public java.util.List<bot.cline.host.proto.ContentDiff> getDiffsList() {
      if (diffsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(diffs_);
      } else {
        return diffsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public int getDiffsCount() {
      if (diffsBuilder_ == null) {
        return diffs_.size();
      } else {
        return diffsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public bot.cline.host.proto.ContentDiff getDiffs(int index) {
      if (diffsBuilder_ == null) {
        return diffs_.get(index);
      } else {
        return diffsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder setDiffs(
        int index, bot.cline.host.proto.ContentDiff value) {
      if (diffsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffsIsMutable();
        diffs_.set(index, value);
        onChanged();
      } else {
        diffsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder setDiffs(
        int index, bot.cline.host.proto.ContentDiff.Builder builderForValue) {
      if (diffsBuilder_ == null) {
        ensureDiffsIsMutable();
        diffs_.set(index, builderForValue.build());
        onChanged();
      } else {
        diffsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder addDiffs(bot.cline.host.proto.ContentDiff value) {
      if (diffsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffsIsMutable();
        diffs_.add(value);
        onChanged();
      } else {
        diffsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder addDiffs(
        int index, bot.cline.host.proto.ContentDiff value) {
      if (diffsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffsIsMutable();
        diffs_.add(index, value);
        onChanged();
      } else {
        diffsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder addDiffs(
        bot.cline.host.proto.ContentDiff.Builder builderForValue) {
      if (diffsBuilder_ == null) {
        ensureDiffsIsMutable();
        diffs_.add(builderForValue.build());
        onChanged();
      } else {
        diffsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder addDiffs(
        int index, bot.cline.host.proto.ContentDiff.Builder builderForValue) {
      if (diffsBuilder_ == null) {
        ensureDiffsIsMutable();
        diffs_.add(index, builderForValue.build());
        onChanged();
      } else {
        diffsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder addAllDiffs(
        java.lang.Iterable<? extends bot.cline.host.proto.ContentDiff> values) {
      if (diffsBuilder_ == null) {
        ensureDiffsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, diffs_);
        onChanged();
      } else {
        diffsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder clearDiffs() {
      if (diffsBuilder_ == null) {
        diffs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        diffsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public Builder removeDiffs(int index) {
      if (diffsBuilder_ == null) {
        ensureDiffsIsMutable();
        diffs_.remove(index);
        onChanged();
      } else {
        diffsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public bot.cline.host.proto.ContentDiff.Builder getDiffsBuilder(
        int index) {
      return getDiffsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public bot.cline.host.proto.ContentDiffOrBuilder getDiffsOrBuilder(
        int index) {
      if (diffsBuilder_ == null) {
        return diffs_.get(index);  } else {
        return diffsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public java.util.List<? extends bot.cline.host.proto.ContentDiffOrBuilder> 
         getDiffsOrBuilderList() {
      if (diffsBuilder_ != null) {
        return diffsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(diffs_);
      }
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public bot.cline.host.proto.ContentDiff.Builder addDiffsBuilder() {
      return getDiffsFieldBuilder().addBuilder(
          bot.cline.host.proto.ContentDiff.getDefaultInstance());
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public bot.cline.host.proto.ContentDiff.Builder addDiffsBuilder(
        int index) {
      return getDiffsFieldBuilder().addBuilder(
          index, bot.cline.host.proto.ContentDiff.getDefaultInstance());
    }
    /**
     * <code>repeated .host.ContentDiff diffs = 2;</code>
     */
    public java.util.List<bot.cline.host.proto.ContentDiff.Builder> 
         getDiffsBuilderList() {
      return getDiffsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bot.cline.host.proto.ContentDiff, bot.cline.host.proto.ContentDiff.Builder, bot.cline.host.proto.ContentDiffOrBuilder> 
        getDiffsFieldBuilder() {
      if (diffsBuilder_ == null) {
        diffsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bot.cline.host.proto.ContentDiff, bot.cline.host.proto.ContentDiff.Builder, bot.cline.host.proto.ContentDiffOrBuilder>(
                diffs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        diffs_ = null;
      }
      return diffsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.OpenMultiFileDiffRequest)
  }

  // @@protoc_insertion_point(class_scope:host.OpenMultiFileDiffRequest)
  private static final bot.cline.host.proto.OpenMultiFileDiffRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.OpenMultiFileDiffRequest();
  }

  public static bot.cline.host.proto.OpenMultiFileDiffRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OpenMultiFileDiffRequest>
      PARSER = new com.google.protobuf.AbstractParser<OpenMultiFileDiffRequest>() {
    @java.lang.Override
    public OpenMultiFileDiffRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OpenMultiFileDiffRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OpenMultiFileDiffRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpenMultiFileDiffRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.OpenMultiFileDiffRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

