// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

public interface ReplaceTextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ReplaceTextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  bot.cline.proto.Metadata getMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   */
  bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>optional string diff_id = 2;</code>
   * @return Whether the diffId field is set.
   */
  boolean hasDiffId();
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The diffId.
   */
  java.lang.String getDiffId();
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The bytes for diffId.
   */
  com.google.protobuf.ByteString
      getDiffIdBytes();

  /**
   * <code>optional string content = 3;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>optional int32 start_line = 4;</code>
   * @return Whether the startLine field is set.
   */
  boolean hasStartLine();
  /**
   * <code>optional int32 start_line = 4;</code>
   * @return The startLine.
   */
  int getStartLine();

  /**
   * <code>optional int32 end_line = 5;</code>
   * @return Whether the endLine field is set.
   */
  boolean hasEndLine();
  /**
   * <code>optional int32 end_line = 5;</code>
   * @return The endLine.
   */
  int getEndLine();
}
