// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

/**
 * Protobuf type {@code host.ReplaceTextRequest}
 */
public final class ReplaceTextRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.ReplaceTextRequest)
    ReplaceTextRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplaceTextRequest.newBuilder() to construct.
  private ReplaceTextRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplaceTextRequest() {
    diffId_ = "";
    content_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReplaceTextRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplaceTextRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            bot.cline.proto.Metadata.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(bot.cline.proto.Metadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            diffId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            content_ = s;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            startLine_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            endLine_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Diff.internal_static_host_ReplaceTextRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Diff.internal_static_host_ReplaceTextRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.ReplaceTextRequest.class, bot.cline.host.proto.ReplaceTextRequest.Builder.class);
  }

  private int bitField0_;
  public static final int METADATA_FIELD_NUMBER = 1;
  private bot.cline.proto.Metadata metadata_;
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public bot.cline.proto.Metadata getMetadata() {
    return metadata_ == null ? bot.cline.proto.Metadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   */
  @java.lang.Override
  public bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? bot.cline.proto.Metadata.getDefaultInstance() : metadata_;
  }

  public static final int DIFF_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object diffId_;
  /**
   * <code>optional string diff_id = 2;</code>
   * @return Whether the diffId field is set.
   */
  @java.lang.Override
  public boolean hasDiffId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The diffId.
   */
  @java.lang.Override
  public java.lang.String getDiffId() {
    java.lang.Object ref = diffId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      diffId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The bytes for diffId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiffIdBytes() {
    java.lang.Object ref = diffId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      diffId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object content_;
  /**
   * <code>optional string content = 3;</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>optional string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_LINE_FIELD_NUMBER = 4;
  private int startLine_;
  /**
   * <code>optional int32 start_line = 4;</code>
   * @return Whether the startLine field is set.
   */
  @java.lang.Override
  public boolean hasStartLine() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 start_line = 4;</code>
   * @return The startLine.
   */
  @java.lang.Override
  public int getStartLine() {
    return startLine_;
  }

  public static final int END_LINE_FIELD_NUMBER = 5;
  private int endLine_;
  /**
   * <code>optional int32 end_line = 5;</code>
   * @return Whether the endLine field is set.
   */
  @java.lang.Override
  public boolean hasEndLine() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 end_line = 5;</code>
   * @return The endLine.
   */
  @java.lang.Override
  public int getEndLine() {
    return endLine_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMetadata());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, diffId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, startLine_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, endLine_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadata());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, diffId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, startLine_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, endLine_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.ReplaceTextRequest)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.ReplaceTextRequest other = (bot.cline.host.proto.ReplaceTextRequest) obj;

    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (hasDiffId() != other.hasDiffId()) return false;
    if (hasDiffId()) {
      if (!getDiffId()
          .equals(other.getDiffId())) return false;
    }
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (hasStartLine() != other.hasStartLine()) return false;
    if (hasStartLine()) {
      if (getStartLine()
          != other.getStartLine()) return false;
    }
    if (hasEndLine() != other.hasEndLine()) return false;
    if (hasEndLine()) {
      if (getEndLine()
          != other.getEndLine()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (hasDiffId()) {
      hash = (37 * hash) + DIFF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDiffId().hashCode();
    }
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    if (hasStartLine()) {
      hash = (37 * hash) + START_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getStartLine();
    }
    if (hasEndLine()) {
      hash = (37 * hash) + END_LINE_FIELD_NUMBER;
      hash = (53 * hash) + getEndLine();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ReplaceTextRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.ReplaceTextRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code host.ReplaceTextRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.ReplaceTextRequest)
      bot.cline.host.proto.ReplaceTextRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Diff.internal_static_host_ReplaceTextRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Diff.internal_static_host_ReplaceTextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.ReplaceTextRequest.class, bot.cline.host.proto.ReplaceTextRequest.Builder.class);
    }

    // Construct using bot.cline.host.proto.ReplaceTextRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      diffId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      content_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      startLine_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      endLine_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Diff.internal_static_host_ReplaceTextRequest_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.ReplaceTextRequest getDefaultInstanceForType() {
      return bot.cline.host.proto.ReplaceTextRequest.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.ReplaceTextRequest build() {
      bot.cline.host.proto.ReplaceTextRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.ReplaceTextRequest buildPartial() {
      bot.cline.host.proto.ReplaceTextRequest result = new bot.cline.host.proto.ReplaceTextRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.diffId_ = diffId_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.content_ = content_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.startLine_ = startLine_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.endLine_ = endLine_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.ReplaceTextRequest) {
        return mergeFrom((bot.cline.host.proto.ReplaceTextRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.ReplaceTextRequest other) {
      if (other == bot.cline.host.proto.ReplaceTextRequest.getDefaultInstance()) return this;
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.hasDiffId()) {
        bitField0_ |= 0x00000002;
        diffId_ = other.diffId_;
        onChanged();
      }
      if (other.hasContent()) {
        bitField0_ |= 0x00000004;
        content_ = other.content_;
        onChanged();
      }
      if (other.hasStartLine()) {
        setStartLine(other.getStartLine());
      }
      if (other.hasEndLine()) {
        setEndLine(other.getEndLine());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.ReplaceTextRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.ReplaceTextRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private bot.cline.proto.Metadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bot.cline.proto.Metadata, bot.cline.proto.Metadata.Builder, bot.cline.proto.MetadataOrBuilder> metadataBuilder_;
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     * @return The metadata.
     */
    public bot.cline.proto.Metadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? bot.cline.proto.Metadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public Builder setMetadata(bot.cline.proto.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public Builder setMetadata(
        bot.cline.proto.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public Builder mergeMetadata(bot.cline.proto.Metadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            metadata_ != null &&
            metadata_ != bot.cline.proto.Metadata.getDefaultInstance()) {
          metadata_ =
            bot.cline.proto.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public bot.cline.proto.Metadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    public bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            bot.cline.proto.Metadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>optional .cline.Metadata metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bot.cline.proto.Metadata, bot.cline.proto.Metadata.Builder, bot.cline.proto.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bot.cline.proto.Metadata, bot.cline.proto.Metadata.Builder, bot.cline.proto.MetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.lang.Object diffId_ = "";
    /**
     * <code>optional string diff_id = 2;</code>
     * @return Whether the diffId field is set.
     */
    public boolean hasDiffId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string diff_id = 2;</code>
     * @return The diffId.
     */
    public java.lang.String getDiffId() {
      java.lang.Object ref = diffId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diffId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string diff_id = 2;</code>
     * @return The bytes for diffId.
     */
    public com.google.protobuf.ByteString
        getDiffIdBytes() {
      java.lang.Object ref = diffId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diffId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string diff_id = 2;</code>
     * @param value The diffId to set.
     * @return This builder for chaining.
     */
    public Builder setDiffId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      diffId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string diff_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiffId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      diffId_ = getDefaultInstance().getDiffId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string diff_id = 2;</code>
     * @param value The bytes for diffId to set.
     * @return This builder for chaining.
     */
    public Builder setDiffIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      diffId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>optional string content = 3;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      content_ = value;
      onChanged();
      return this;
    }

    private int startLine_ ;
    /**
     * <code>optional int32 start_line = 4;</code>
     * @return Whether the startLine field is set.
     */
    @java.lang.Override
    public boolean hasStartLine() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 start_line = 4;</code>
     * @return The startLine.
     */
    @java.lang.Override
    public int getStartLine() {
      return startLine_;
    }
    /**
     * <code>optional int32 start_line = 4;</code>
     * @param value The startLine to set.
     * @return This builder for chaining.
     */
    public Builder setStartLine(int value) {
      bitField0_ |= 0x00000008;
      startLine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 start_line = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartLine() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startLine_ = 0;
      onChanged();
      return this;
    }

    private int endLine_ ;
    /**
     * <code>optional int32 end_line = 5;</code>
     * @return Whether the endLine field is set.
     */
    @java.lang.Override
    public boolean hasEndLine() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 end_line = 5;</code>
     * @return The endLine.
     */
    @java.lang.Override
    public int getEndLine() {
      return endLine_;
    }
    /**
     * <code>optional int32 end_line = 5;</code>
     * @param value The endLine to set.
     * @return This builder for chaining.
     */
    public Builder setEndLine(int value) {
      bitField0_ |= 0x00000010;
      endLine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 end_line = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndLine() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endLine_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.ReplaceTextRequest)
  }

  // @@protoc_insertion_point(class_scope:host.ReplaceTextRequest)
  private static final bot.cline.host.proto.ReplaceTextRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.ReplaceTextRequest();
  }

  public static bot.cline.host.proto.ReplaceTextRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplaceTextRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReplaceTextRequest>() {
    @java.lang.Override
    public ReplaceTextRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplaceTextRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplaceTextRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplaceTextRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.ReplaceTextRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

