// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

public interface SaveDocumentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.SaveDocumentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   * @return The metadata.
   */
  bot.cline.proto.Metadata getMetadata();
  /**
   * <code>optional .cline.Metadata metadata = 1;</code>
   */
  bot.cline.proto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>optional string diff_id = 2;</code>
   * @return Whether the diffId field is set.
   */
  boolean hasDiffId();
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The diffId.
   */
  java.lang.String getDiffId();
  /**
   * <code>optional string diff_id = 2;</code>
   * @return The bytes for diffId.
   */
  com.google.protobuf.ByteString
      getDiffIdBytes();
}
