// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/diff.proto

package bot.cline.host.proto;

public interface ScrollDiffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ScrollDiffResponse)
    com.google.protobuf.MessageOrBuilder {
}
