// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

/**
 * <pre>
 * Request for host-side workspace search (files/folders) used by mentions autocomplete
 * </pre>
 *
 * Protobuf type {@code host.SearchWorkspaceItemsRequest}
 */
public final class SearchWorkspaceItemsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.SearchWorkspaceItemsRequest)
    SearchWorkspaceItemsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchWorkspaceItemsRequest.newBuilder() to construct.
  private SearchWorkspaceItemsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchWorkspaceItemsRequest() {
    query_ = "";
    selectedType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchWorkspaceItemsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchWorkspaceItemsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            query_ = s;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000001;
            limit_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
            bitField0_ |= 0x00000002;
            selectedType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.SearchWorkspaceItemsRequest.class, bot.cline.host.proto.SearchWorkspaceItemsRequest.Builder.class);
  }

  /**
   * <pre>
   * Optional selected type filter
   * </pre>
   *
   * Protobuf enum {@code host.SearchWorkspaceItemsRequest.SearchItemType}
   */
  public enum SearchItemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FILE = 0;</code>
     */
    FILE(0),
    /**
     * <code>FOLDER = 1;</code>
     */
    FOLDER(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FILE = 0;</code>
     */
    public static final int FILE_VALUE = 0;
    /**
     * <code>FOLDER = 1;</code>
     */
    public static final int FOLDER_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SearchItemType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SearchItemType forNumber(int value) {
      switch (value) {
        case 0: return FILE;
        case 1: return FOLDER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SearchItemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SearchItemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SearchItemType>() {
            public SearchItemType findValueByNumber(int number) {
              return SearchItemType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return bot.cline.host.proto.SearchWorkspaceItemsRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final SearchItemType[] VALUES = values();

    public static SearchItemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SearchItemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:host.SearchWorkspaceItemsRequest.SearchItemType)
  }

  private int bitField0_;
  public static final int QUERY_FIELD_NUMBER = 1;
  private volatile java.lang.Object query_;
  /**
   * <pre>
   * Search query string
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Search query string
   * </pre>
   *
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_;
  /**
   * <pre>
   * Optional limit for results (default decided by host)
   * </pre>
   *
   * <code>optional int32 limit = 2;</code>
   * @return Whether the limit field is set.
   */
  @java.lang.Override
  public boolean hasLimit() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional limit for results (default decided by host)
   * </pre>
   *
   * <code>optional int32 limit = 2;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  public static final int SELECTED_TYPE_FIELD_NUMBER = 3;
  private int selectedType_;
  /**
   * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
   * @return Whether the selectedType field is set.
   */
  @java.lang.Override public boolean hasSelectedType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
   * @return The enum numeric value on the wire for selectedType.
   */
  @java.lang.Override public int getSelectedTypeValue() {
    return selectedType_;
  }
  /**
   * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
   * @return The selectedType.
   */
  @java.lang.Override public bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType getSelectedType() {
    @SuppressWarnings("deprecation")
    bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType result = bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.valueOf(selectedType_);
    return result == null ? bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, limit_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(3, selectedType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, limit_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, selectedType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.SearchWorkspaceItemsRequest)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.SearchWorkspaceItemsRequest other = (bot.cline.host.proto.SearchWorkspaceItemsRequest) obj;

    if (!getQuery()
        .equals(other.getQuery())) return false;
    if (hasLimit() != other.hasLimit()) return false;
    if (hasLimit()) {
      if (getLimit()
          != other.getLimit()) return false;
    }
    if (hasSelectedType() != other.hasSelectedType()) return false;
    if (hasSelectedType()) {
      if (selectedType_ != other.selectedType_) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    if (hasLimit()) {
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
    }
    if (hasSelectedType()) {
      hash = (37 * hash) + SELECTED_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + selectedType_;
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.SearchWorkspaceItemsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request for host-side workspace search (files/folders) used by mentions autocomplete
   * </pre>
   *
   * Protobuf type {@code host.SearchWorkspaceItemsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.SearchWorkspaceItemsRequest)
      bot.cline.host.proto.SearchWorkspaceItemsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.SearchWorkspaceItemsRequest.class, bot.cline.host.proto.SearchWorkspaceItemsRequest.Builder.class);
    }

    // Construct using bot.cline.host.proto.SearchWorkspaceItemsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      query_ = "";

      limit_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      selectedType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsRequest_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsRequest getDefaultInstanceForType() {
      return bot.cline.host.proto.SearchWorkspaceItemsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsRequest build() {
      bot.cline.host.proto.SearchWorkspaceItemsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsRequest buildPartial() {
      bot.cline.host.proto.SearchWorkspaceItemsRequest result = new bot.cline.host.proto.SearchWorkspaceItemsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.query_ = query_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.limit_ = limit_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.selectedType_ = selectedType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.SearchWorkspaceItemsRequest) {
        return mergeFrom((bot.cline.host.proto.SearchWorkspaceItemsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.SearchWorkspaceItemsRequest other) {
      if (other == bot.cline.host.proto.SearchWorkspaceItemsRequest.getDefaultInstance()) return this;
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        onChanged();
      }
      if (other.hasLimit()) {
        setLimit(other.getLimit());
      }
      if (other.hasSelectedType()) {
        setSelectedType(other.getSelectedType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.SearchWorkspaceItemsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.SearchWorkspaceItemsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object query_ = "";
    /**
     * <pre>
     * Search query string
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Search query string
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Search query string
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Search query string
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Search query string
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      query_ = value;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <pre>
     * Optional limit for results (default decided by host)
     * </pre>
     *
     * <code>optional int32 limit = 2;</code>
     * @return Whether the limit field is set.
     */
    @java.lang.Override
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional limit for results (default decided by host)
     * </pre>
     *
     * <code>optional int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <pre>
     * Optional limit for results (default decided by host)
     * </pre>
     *
     * <code>optional int32 limit = 2;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      bitField0_ |= 0x00000001;
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional limit for results (default decided by host)
     * </pre>
     *
     * <code>optional int32 limit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      limit_ = 0;
      onChanged();
      return this;
    }

    private int selectedType_ = 0;
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @return Whether the selectedType field is set.
     */
    @java.lang.Override public boolean hasSelectedType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @return The enum numeric value on the wire for selectedType.
     */
    @java.lang.Override public int getSelectedTypeValue() {
      return selectedType_;
    }
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @param value The enum numeric value on the wire for selectedType to set.
     * @return This builder for chaining.
     */
    public Builder setSelectedTypeValue(int value) {
      bitField0_ |= 0x00000002;
      selectedType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @return The selectedType.
     */
    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType getSelectedType() {
      @SuppressWarnings("deprecation")
      bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType result = bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.valueOf(selectedType_);
      return result == null ? bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @param value The selectedType to set.
     * @return This builder for chaining.
     */
    public Builder setSelectedType(bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      selectedType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .host.SearchWorkspaceItemsRequest.SearchItemType selected_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectedType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      selectedType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.SearchWorkspaceItemsRequest)
  }

  // @@protoc_insertion_point(class_scope:host.SearchWorkspaceItemsRequest)
  private static final bot.cline.host.proto.SearchWorkspaceItemsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.SearchWorkspaceItemsRequest();
  }

  public static bot.cline.host.proto.SearchWorkspaceItemsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchWorkspaceItemsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SearchWorkspaceItemsRequest>() {
    @java.lang.Override
    public SearchWorkspaceItemsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchWorkspaceItemsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchWorkspaceItemsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchWorkspaceItemsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.SearchWorkspaceItemsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

