// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/workspace.proto

package bot.cline.host.proto;

/**
 * <pre>
 * Response for host-side workspace search
 * </pre>
 *
 * Protobuf type {@code host.SearchWorkspaceItemsResponse}
 */
public final class SearchWorkspaceItemsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.SearchWorkspaceItemsResponse)
    SearchWorkspaceItemsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchWorkspaceItemsResponse.newBuilder() to construct.
  private SearchWorkspaceItemsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchWorkspaceItemsResponse() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchWorkspaceItemsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchWorkspaceItemsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.SearchWorkspaceItemsResponse.class, bot.cline.host.proto.SearchWorkspaceItemsResponse.Builder.class);
  }

  public interface SearchItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:host.SearchWorkspaceItemsResponse.SearchItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Workspace-relative path using platform separators
     * </pre>
     *
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <pre>
     * Workspace-relative path using platform separators
     * </pre>
     *
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
     * @return The type.
     */
    bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType getType();

    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return Whether the label field is set.
     */
    boolean hasLabel();
    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code host.SearchWorkspaceItemsResponse.SearchItem}
   */
  public static final class SearchItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:host.SearchWorkspaceItemsResponse.SearchItem)
      SearchItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchItem.newBuilder() to construct.
    private SearchItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchItem() {
      path_ = "";
      type_ = 0;
      label_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              label_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_SearchItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_SearchItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.class, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder.class);
    }

    private int bitField0_;
    public static final int PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * Workspace-relative path using platform separators
     * </pre>
     *
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Workspace-relative path using platform separators
     * </pre>
     *
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType getType() {
      @SuppressWarnings("deprecation")
      bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType result = bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.valueOf(type_);
      return result == null ? bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.UNRECOGNIZED : result;
    }

    public static final int LABEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object label_;
    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional display label (e.g., basename)
     * </pre>
     *
     * <code>optional string label = 3;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
      }
      if (type_ != bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.FILE.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, label_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
      }
      if (type_ != bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.FILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, label_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem)) {
        return super.equals(obj);
      }
      bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem other = (bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem) obj;

      if (!getPath()
          .equals(other.getPath())) return false;
      if (type_ != other.type_) return false;
      if (hasLabel() != other.hasLabel()) return false;
      if (hasLabel()) {
        if (!getLabel()
            .equals(other.getLabel())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code host.SearchWorkspaceItemsResponse.SearchItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:host.SearchWorkspaceItemsResponse.SearchItem)
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_SearchItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_SearchItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.class, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder.class);
      }

      // Construct using bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        path_ = "";

        type_ = 0;

        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_SearchItem_descriptor;
      }

      @java.lang.Override
      public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem getDefaultInstanceForType() {
        return bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.getDefaultInstance();
      }

      @java.lang.Override
      public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem build() {
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem buildPartial() {
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem result = new bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.path_ = path_;
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.label_ = label_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem) {
          return mergeFrom((bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem other) {
        if (other == bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.getDefaultInstance()) return this;
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000001;
          label_ = other.label_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * Workspace-relative path using platform separators
       * </pre>
       *
       * <code>string path = 1;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Workspace-relative path using platform separators
       * </pre>
       *
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Workspace-relative path using platform separators
       * </pre>
       *
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Workspace-relative path using platform separators
       * </pre>
       *
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Workspace-relative path using platform separators
       * </pre>
       *
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType getType() {
        @SuppressWarnings("deprecation")
        bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType result = bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.valueOf(type_);
        return result == null ? bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType.UNRECOGNIZED : result;
      }
      /**
       * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(bot.cline.host.proto.SearchWorkspaceItemsRequest.SearchItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.host.SearchWorkspaceItemsRequest.SearchItemType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @return Whether the label field is set.
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional display label (e.g., basename)
       * </pre>
       *
       * <code>optional string label = 3;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:host.SearchWorkspaceItemsResponse.SearchItem)
    }

    // @@protoc_insertion_point(class_scope:host.SearchWorkspaceItemsResponse.SearchItem)
    private static final bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem();
    }

    public static bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchItem>
        PARSER = new com.google.protobuf.AbstractParser<SearchItem>() {
      @java.lang.Override
      public SearchItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem> items_;
  /**
   * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
   */
  @java.lang.Override
  public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
   */
  @java.lang.Override
  public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.SearchWorkspaceItemsResponse)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.SearchWorkspaceItemsResponse other = (bot.cline.host.proto.SearchWorkspaceItemsResponse) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.SearchWorkspaceItemsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.SearchWorkspaceItemsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response for host-side workspace search
   * </pre>
   *
   * Protobuf type {@code host.SearchWorkspaceItemsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.SearchWorkspaceItemsResponse)
      bot.cline.host.proto.SearchWorkspaceItemsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.SearchWorkspaceItemsResponse.class, bot.cline.host.proto.SearchWorkspaceItemsResponse.Builder.class);
    }

    // Construct using bot.cline.host.proto.SearchWorkspaceItemsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Workspace.internal_static_host_SearchWorkspaceItemsResponse_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsResponse getDefaultInstanceForType() {
      return bot.cline.host.proto.SearchWorkspaceItemsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsResponse build() {
      bot.cline.host.proto.SearchWorkspaceItemsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.SearchWorkspaceItemsResponse buildPartial() {
      bot.cline.host.proto.SearchWorkspaceItemsResponse result = new bot.cline.host.proto.SearchWorkspaceItemsResponse(this);
      int from_bitField0_ = bitField0_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.SearchWorkspaceItemsResponse) {
        return mergeFrom((bot.cline.host.proto.SearchWorkspaceItemsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.SearchWorkspaceItemsResponse other) {
      if (other == bot.cline.host.proto.SearchWorkspaceItemsResponse.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.SearchWorkspaceItemsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.SearchWorkspaceItemsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public java.util.List<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder setItems(
        int index, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder setItems(
        int index, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder addItems(bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder addItems(
        int index, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder addItems(
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder addItems(
        int index, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public java.util.List<? extends bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.getDefaultInstance());
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.getDefaultInstance());
    }
    /**
     * <code>repeated .host.SearchWorkspaceItemsResponse.SearchItem items = 1;</code>
     */
    public java.util.List<bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItem.Builder, bot.cline.host.proto.SearchWorkspaceItemsResponse.SearchItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.SearchWorkspaceItemsResponse)
  }

  // @@protoc_insertion_point(class_scope:host.SearchWorkspaceItemsResponse)
  private static final bot.cline.host.proto.SearchWorkspaceItemsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.SearchWorkspaceItemsResponse();
  }

  public static bot.cline.host.proto.SearchWorkspaceItemsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchWorkspaceItemsResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchWorkspaceItemsResponse>() {
    @java.lang.Override
    public SearchWorkspaceItemsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchWorkspaceItemsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchWorkspaceItemsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchWorkspaceItemsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.SearchWorkspaceItemsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

