// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface ShowOpenDialogueFilterOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ShowOpenDialogueFilterOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string files = 1;</code>
   * @return A list containing the files.
   */
  java.util.List<java.lang.String>
      getFilesList();
  /**
   * <code>repeated string files = 1;</code>
   * @return The count of files.
   */
  int getFilesCount();
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  java.lang.String getFiles(int index);
  /**
   * <code>repeated string files = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  com.google.protobuf.ByteString
      getFilesBytes(int index);
}
