// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

/**
 * Protobuf type {@code host.ShowOpenDialogueRequest}
 */
public final class ShowOpenDialogueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.ShowOpenDialogueRequest)
    ShowOpenDialogueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShowOpenDialogueRequest.newBuilder() to construct.
  private ShowOpenDialogueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShowOpenDialogueRequest() {
    openLabel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShowOpenDialogueRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShowOpenDialogueRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {
            bitField0_ |= 0x00000001;
            canSelectMany_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            openLabel_ = s;
            break;
          }
          case 34: {
            bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = filters_.toBuilder();
            }
            filters_ = input.readMessage(bot.cline.host.proto.ShowOpenDialogueFilterOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filters_);
              filters_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Window.internal_static_host_ShowOpenDialogueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Window.internal_static_host_ShowOpenDialogueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.ShowOpenDialogueRequest.class, bot.cline.host.proto.ShowOpenDialogueRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CAN_SELECT_MANY_FIELD_NUMBER = 2;
  private boolean canSelectMany_;
  /**
   * <code>optional bool can_select_many = 2;</code>
   * @return Whether the canSelectMany field is set.
   */
  @java.lang.Override
  public boolean hasCanSelectMany() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool can_select_many = 2;</code>
   * @return The canSelectMany.
   */
  @java.lang.Override
  public boolean getCanSelectMany() {
    return canSelectMany_;
  }

  public static final int OPEN_LABEL_FIELD_NUMBER = 3;
  private volatile java.lang.Object openLabel_;
  /**
   * <code>optional string open_label = 3;</code>
   * @return Whether the openLabel field is set.
   */
  @java.lang.Override
  public boolean hasOpenLabel() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string open_label = 3;</code>
   * @return The openLabel.
   */
  @java.lang.Override
  public java.lang.String getOpenLabel() {
    java.lang.Object ref = openLabel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      openLabel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string open_label = 3;</code>
   * @return The bytes for openLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpenLabelBytes() {
    java.lang.Object ref = openLabel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      openLabel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTERS_FIELD_NUMBER = 4;
  private bot.cline.host.proto.ShowOpenDialogueFilterOption filters_;
  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   * @return Whether the filters field is set.
   */
  @java.lang.Override
  public boolean hasFilters() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   * @return The filters.
   */
  @java.lang.Override
  public bot.cline.host.proto.ShowOpenDialogueFilterOption getFilters() {
    return filters_ == null ? bot.cline.host.proto.ShowOpenDialogueFilterOption.getDefaultInstance() : filters_;
  }
  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   */
  @java.lang.Override
  public bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder getFiltersOrBuilder() {
    return filters_ == null ? bot.cline.host.proto.ShowOpenDialogueFilterOption.getDefaultInstance() : filters_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(2, canSelectMany_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, openLabel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getFilters());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, canSelectMany_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, openLabel_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFilters());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.ShowOpenDialogueRequest)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.ShowOpenDialogueRequest other = (bot.cline.host.proto.ShowOpenDialogueRequest) obj;

    if (hasCanSelectMany() != other.hasCanSelectMany()) return false;
    if (hasCanSelectMany()) {
      if (getCanSelectMany()
          != other.getCanSelectMany()) return false;
    }
    if (hasOpenLabel() != other.hasOpenLabel()) return false;
    if (hasOpenLabel()) {
      if (!getOpenLabel()
          .equals(other.getOpenLabel())) return false;
    }
    if (hasFilters() != other.hasFilters()) return false;
    if (hasFilters()) {
      if (!getFilters()
          .equals(other.getFilters())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCanSelectMany()) {
      hash = (37 * hash) + CAN_SELECT_MANY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCanSelectMany());
    }
    if (hasOpenLabel()) {
      hash = (37 * hash) + OPEN_LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getOpenLabel().hashCode();
    }
    if (hasFilters()) {
      hash = (37 * hash) + FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + getFilters().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowOpenDialogueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.ShowOpenDialogueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code host.ShowOpenDialogueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.ShowOpenDialogueRequest)
      bot.cline.host.proto.ShowOpenDialogueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Window.internal_static_host_ShowOpenDialogueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Window.internal_static_host_ShowOpenDialogueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.ShowOpenDialogueRequest.class, bot.cline.host.proto.ShowOpenDialogueRequest.Builder.class);
    }

    // Construct using bot.cline.host.proto.ShowOpenDialogueRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFiltersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      canSelectMany_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      openLabel_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (filtersBuilder_ == null) {
        filters_ = null;
      } else {
        filtersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Window.internal_static_host_ShowOpenDialogueRequest_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowOpenDialogueRequest getDefaultInstanceForType() {
      return bot.cline.host.proto.ShowOpenDialogueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowOpenDialogueRequest build() {
      bot.cline.host.proto.ShowOpenDialogueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowOpenDialogueRequest buildPartial() {
      bot.cline.host.proto.ShowOpenDialogueRequest result = new bot.cline.host.proto.ShowOpenDialogueRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.canSelectMany_ = canSelectMany_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.openLabel_ = openLabel_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (filtersBuilder_ == null) {
          result.filters_ = filters_;
        } else {
          result.filters_ = filtersBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.ShowOpenDialogueRequest) {
        return mergeFrom((bot.cline.host.proto.ShowOpenDialogueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.ShowOpenDialogueRequest other) {
      if (other == bot.cline.host.proto.ShowOpenDialogueRequest.getDefaultInstance()) return this;
      if (other.hasCanSelectMany()) {
        setCanSelectMany(other.getCanSelectMany());
      }
      if (other.hasOpenLabel()) {
        bitField0_ |= 0x00000002;
        openLabel_ = other.openLabel_;
        onChanged();
      }
      if (other.hasFilters()) {
        mergeFilters(other.getFilters());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.ShowOpenDialogueRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.ShowOpenDialogueRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean canSelectMany_ ;
    /**
     * <code>optional bool can_select_many = 2;</code>
     * @return Whether the canSelectMany field is set.
     */
    @java.lang.Override
    public boolean hasCanSelectMany() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool can_select_many = 2;</code>
     * @return The canSelectMany.
     */
    @java.lang.Override
    public boolean getCanSelectMany() {
      return canSelectMany_;
    }
    /**
     * <code>optional bool can_select_many = 2;</code>
     * @param value The canSelectMany to set.
     * @return This builder for chaining.
     */
    public Builder setCanSelectMany(boolean value) {
      bitField0_ |= 0x00000001;
      canSelectMany_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool can_select_many = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanSelectMany() {
      bitField0_ = (bitField0_ & ~0x00000001);
      canSelectMany_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object openLabel_ = "";
    /**
     * <code>optional string open_label = 3;</code>
     * @return Whether the openLabel field is set.
     */
    public boolean hasOpenLabel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string open_label = 3;</code>
     * @return The openLabel.
     */
    public java.lang.String getOpenLabel() {
      java.lang.Object ref = openLabel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        openLabel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string open_label = 3;</code>
     * @return The bytes for openLabel.
     */
    public com.google.protobuf.ByteString
        getOpenLabelBytes() {
      java.lang.Object ref = openLabel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string open_label = 3;</code>
     * @param value The openLabel to set.
     * @return This builder for chaining.
     */
    public Builder setOpenLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      openLabel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string open_label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpenLabel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      openLabel_ = getDefaultInstance().getOpenLabel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string open_label = 3;</code>
     * @param value The bytes for openLabel to set.
     * @return This builder for chaining.
     */
    public Builder setOpenLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      openLabel_ = value;
      onChanged();
      return this;
    }

    private bot.cline.host.proto.ShowOpenDialogueFilterOption filters_;
    private com.google.protobuf.SingleFieldBuilderV3<
        bot.cline.host.proto.ShowOpenDialogueFilterOption, bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder, bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder> filtersBuilder_;
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     * @return Whether the filters field is set.
     */
    public boolean hasFilters() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     * @return The filters.
     */
    public bot.cline.host.proto.ShowOpenDialogueFilterOption getFilters() {
      if (filtersBuilder_ == null) {
        return filters_ == null ? bot.cline.host.proto.ShowOpenDialogueFilterOption.getDefaultInstance() : filters_;
      } else {
        return filtersBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public Builder setFilters(bot.cline.host.proto.ShowOpenDialogueFilterOption value) {
      if (filtersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filters_ = value;
        onChanged();
      } else {
        filtersBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public Builder setFilters(
        bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder builderForValue) {
      if (filtersBuilder_ == null) {
        filters_ = builderForValue.build();
        onChanged();
      } else {
        filtersBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public Builder mergeFilters(bot.cline.host.proto.ShowOpenDialogueFilterOption value) {
      if (filtersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            filters_ != null &&
            filters_ != bot.cline.host.proto.ShowOpenDialogueFilterOption.getDefaultInstance()) {
          filters_ =
            bot.cline.host.proto.ShowOpenDialogueFilterOption.newBuilder(filters_).mergeFrom(value).buildPartial();
        } else {
          filters_ = value;
        }
        onChanged();
      } else {
        filtersBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public Builder clearFilters() {
      if (filtersBuilder_ == null) {
        filters_ = null;
        onChanged();
      } else {
        filtersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder getFiltersBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getFiltersFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    public bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder getFiltersOrBuilder() {
      if (filtersBuilder_ != null) {
        return filtersBuilder_.getMessageOrBuilder();
      } else {
        return filters_ == null ?
            bot.cline.host.proto.ShowOpenDialogueFilterOption.getDefaultInstance() : filters_;
      }
    }
    /**
     * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bot.cline.host.proto.ShowOpenDialogueFilterOption, bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder, bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder> 
        getFiltersFieldBuilder() {
      if (filtersBuilder_ == null) {
        filtersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bot.cline.host.proto.ShowOpenDialogueFilterOption, bot.cline.host.proto.ShowOpenDialogueFilterOption.Builder, bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder>(
                getFilters(),
                getParentForChildren(),
                isClean());
        filters_ = null;
      }
      return filtersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.ShowOpenDialogueRequest)
  }

  // @@protoc_insertion_point(class_scope:host.ShowOpenDialogueRequest)
  private static final bot.cline.host.proto.ShowOpenDialogueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.ShowOpenDialogueRequest();
  }

  public static bot.cline.host.proto.ShowOpenDialogueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShowOpenDialogueRequest>
      PARSER = new com.google.protobuf.AbstractParser<ShowOpenDialogueRequest>() {
    @java.lang.Override
    public ShowOpenDialogueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShowOpenDialogueRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShowOpenDialogueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShowOpenDialogueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.ShowOpenDialogueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

