// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface ShowTextDocumentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ShowTextDocumentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional .host.ShowTextDocumentOptions options = 3;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>optional .host.ShowTextDocumentOptions options = 3;</code>
   * @return The options.
   */
  bot.cline.host.proto.ShowTextDocumentOptions getOptions();
  /**
   * <code>optional .host.ShowTextDocumentOptions options = 3;</code>
   */
  bot.cline.host.proto.ShowTextDocumentOptionsOrBuilder getOptionsOrBuilder();
}
