// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface ShowSaveDialogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ShowSaveDialogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .host.ShowSaveDialogOptions options = 1;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>optional .host.ShowSaveDialogOptions options = 1;</code>
   * @return The options.
   */
  bot.cline.host.proto.ShowSaveDialogOptions getOptions();
  /**
   * <code>optional .host.ShowSaveDialogOptions options = 1;</code>
   */
  bot.cline.host.proto.ShowSaveDialogOptionsOrBuilder getOptionsOrBuilder();
}
