// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

/**
 * <pre>
 * See https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions
 * </pre>
 *
 * Protobuf type {@code host.ShowTextDocumentOptions}
 */
public final class ShowTextDocumentOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:host.ShowTextDocumentOptions)
    ShowTextDocumentOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShowTextDocumentOptions.newBuilder() to construct.
  private ShowTextDocumentOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShowTextDocumentOptions() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShowTextDocumentOptions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShowTextDocumentOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            preview_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            preserveFocus_ = input.readBool();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            viewColumn_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bot.cline.host.proto.Window.internal_static_host_ShowTextDocumentOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bot.cline.host.proto.Window.internal_static_host_ShowTextDocumentOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bot.cline.host.proto.ShowTextDocumentOptions.class, bot.cline.host.proto.ShowTextDocumentOptions.Builder.class);
  }

  private int bitField0_;
  public static final int PREVIEW_FIELD_NUMBER = 1;
  private boolean preview_;
  /**
   * <code>optional bool preview = 1;</code>
   * @return Whether the preview field is set.
   */
  @java.lang.Override
  public boolean hasPreview() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool preview = 1;</code>
   * @return The preview.
   */
  @java.lang.Override
  public boolean getPreview() {
    return preview_;
  }

  public static final int PRESERVE_FOCUS_FIELD_NUMBER = 2;
  private boolean preserveFocus_;
  /**
   * <code>optional bool preserve_focus = 2;</code>
   * @return Whether the preserveFocus field is set.
   */
  @java.lang.Override
  public boolean hasPreserveFocus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool preserve_focus = 2;</code>
   * @return The preserveFocus.
   */
  @java.lang.Override
  public boolean getPreserveFocus() {
    return preserveFocus_;
  }

  public static final int VIEW_COLUMN_FIELD_NUMBER = 3;
  private int viewColumn_;
  /**
   * <code>optional int32 view_column = 3;</code>
   * @return Whether the viewColumn field is set.
   */
  @java.lang.Override
  public boolean hasViewColumn() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 view_column = 3;</code>
   * @return The viewColumn.
   */
  @java.lang.Override
  public int getViewColumn() {
    return viewColumn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, preview_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, preserveFocus_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, viewColumn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, preview_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, preserveFocus_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, viewColumn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bot.cline.host.proto.ShowTextDocumentOptions)) {
      return super.equals(obj);
    }
    bot.cline.host.proto.ShowTextDocumentOptions other = (bot.cline.host.proto.ShowTextDocumentOptions) obj;

    if (hasPreview() != other.hasPreview()) return false;
    if (hasPreview()) {
      if (getPreview()
          != other.getPreview()) return false;
    }
    if (hasPreserveFocus() != other.hasPreserveFocus()) return false;
    if (hasPreserveFocus()) {
      if (getPreserveFocus()
          != other.getPreserveFocus()) return false;
    }
    if (hasViewColumn() != other.hasViewColumn()) return false;
    if (hasViewColumn()) {
      if (getViewColumn()
          != other.getViewColumn()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPreview()) {
      hash = (37 * hash) + PREVIEW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPreview());
    }
    if (hasPreserveFocus()) {
      hash = (37 * hash) + PRESERVE_FOCUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPreserveFocus());
    }
    if (hasViewColumn()) {
      hash = (37 * hash) + VIEW_COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getViewColumn();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bot.cline.host.proto.ShowTextDocumentOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bot.cline.host.proto.ShowTextDocumentOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * See https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions
   * </pre>
   *
   * Protobuf type {@code host.ShowTextDocumentOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:host.ShowTextDocumentOptions)
      bot.cline.host.proto.ShowTextDocumentOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bot.cline.host.proto.Window.internal_static_host_ShowTextDocumentOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bot.cline.host.proto.Window.internal_static_host_ShowTextDocumentOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bot.cline.host.proto.ShowTextDocumentOptions.class, bot.cline.host.proto.ShowTextDocumentOptions.Builder.class);
    }

    // Construct using bot.cline.host.proto.ShowTextDocumentOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      preview_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      preserveFocus_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      viewColumn_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bot.cline.host.proto.Window.internal_static_host_ShowTextDocumentOptions_descriptor;
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowTextDocumentOptions getDefaultInstanceForType() {
      return bot.cline.host.proto.ShowTextDocumentOptions.getDefaultInstance();
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowTextDocumentOptions build() {
      bot.cline.host.proto.ShowTextDocumentOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public bot.cline.host.proto.ShowTextDocumentOptions buildPartial() {
      bot.cline.host.proto.ShowTextDocumentOptions result = new bot.cline.host.proto.ShowTextDocumentOptions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.preview_ = preview_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.preserveFocus_ = preserveFocus_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.viewColumn_ = viewColumn_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bot.cline.host.proto.ShowTextDocumentOptions) {
        return mergeFrom((bot.cline.host.proto.ShowTextDocumentOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bot.cline.host.proto.ShowTextDocumentOptions other) {
      if (other == bot.cline.host.proto.ShowTextDocumentOptions.getDefaultInstance()) return this;
      if (other.hasPreview()) {
        setPreview(other.getPreview());
      }
      if (other.hasPreserveFocus()) {
        setPreserveFocus(other.getPreserveFocus());
      }
      if (other.hasViewColumn()) {
        setViewColumn(other.getViewColumn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bot.cline.host.proto.ShowTextDocumentOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bot.cline.host.proto.ShowTextDocumentOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean preview_ ;
    /**
     * <code>optional bool preview = 1;</code>
     * @return Whether the preview field is set.
     */
    @java.lang.Override
    public boolean hasPreview() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool preview = 1;</code>
     * @return The preview.
     */
    @java.lang.Override
    public boolean getPreview() {
      return preview_;
    }
    /**
     * <code>optional bool preview = 1;</code>
     * @param value The preview to set.
     * @return This builder for chaining.
     */
    public Builder setPreview(boolean value) {
      bitField0_ |= 0x00000001;
      preview_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool preview = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreview() {
      bitField0_ = (bitField0_ & ~0x00000001);
      preview_ = false;
      onChanged();
      return this;
    }

    private boolean preserveFocus_ ;
    /**
     * <code>optional bool preserve_focus = 2;</code>
     * @return Whether the preserveFocus field is set.
     */
    @java.lang.Override
    public boolean hasPreserveFocus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool preserve_focus = 2;</code>
     * @return The preserveFocus.
     */
    @java.lang.Override
    public boolean getPreserveFocus() {
      return preserveFocus_;
    }
    /**
     * <code>optional bool preserve_focus = 2;</code>
     * @param value The preserveFocus to set.
     * @return This builder for chaining.
     */
    public Builder setPreserveFocus(boolean value) {
      bitField0_ |= 0x00000002;
      preserveFocus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool preserve_focus = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreserveFocus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      preserveFocus_ = false;
      onChanged();
      return this;
    }

    private int viewColumn_ ;
    /**
     * <code>optional int32 view_column = 3;</code>
     * @return Whether the viewColumn field is set.
     */
    @java.lang.Override
    public boolean hasViewColumn() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 view_column = 3;</code>
     * @return The viewColumn.
     */
    @java.lang.Override
    public int getViewColumn() {
      return viewColumn_;
    }
    /**
     * <code>optional int32 view_column = 3;</code>
     * @param value The viewColumn to set.
     * @return This builder for chaining.
     */
    public Builder setViewColumn(int value) {
      bitField0_ |= 0x00000004;
      viewColumn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 view_column = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearViewColumn() {
      bitField0_ = (bitField0_ & ~0x00000004);
      viewColumn_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:host.ShowTextDocumentOptions)
  }

  // @@protoc_insertion_point(class_scope:host.ShowTextDocumentOptions)
  private static final bot.cline.host.proto.ShowTextDocumentOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bot.cline.host.proto.ShowTextDocumentOptions();
  }

  public static bot.cline.host.proto.ShowTextDocumentOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShowTextDocumentOptions>
      PARSER = new com.google.protobuf.AbstractParser<ShowTextDocumentOptions>() {
    @java.lang.Override
    public ShowTextDocumentOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShowTextDocumentOptions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShowTextDocumentOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShowTextDocumentOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public bot.cline.host.proto.ShowTextDocumentOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

