// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface ShowOpenDialogueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ShowOpenDialogueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool can_select_many = 2;</code>
   * @return Whether the canSelectMany field is set.
   */
  boolean hasCanSelectMany();
  /**
   * <code>optional bool can_select_many = 2;</code>
   * @return The canSelectMany.
   */
  boolean getCanSelectMany();

  /**
   * <code>optional string open_label = 3;</code>
   * @return Whether the openLabel field is set.
   */
  boolean hasOpenLabel();
  /**
   * <code>optional string open_label = 3;</code>
   * @return The openLabel.
   */
  java.lang.String getOpenLabel();
  /**
   * <code>optional string open_label = 3;</code>
   * @return The bytes for openLabel.
   */
  com.google.protobuf.ByteString
      getOpenLabelBytes();

  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   * @return Whether the filters field is set.
   */
  boolean hasFilters();
  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   * @return The filters.
   */
  bot.cline.host.proto.ShowOpenDialogueFilterOption getFilters();
  /**
   * <code>optional .host.ShowOpenDialogueFilterOption filters = 4;</code>
   */
  bot.cline.host.proto.ShowOpenDialogueFilterOptionOrBuilder getFiltersOrBuilder();
}
