// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: host/window.proto

package bot.cline.host.proto;

public interface ShowInputBoxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:host.ShowInputBoxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>optional string response = 1;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>optional string response = 1;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
