// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface BytesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.BytesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
