// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface DiagnosticOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.Diagnostic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.cline.DiagnosticRange range = 2;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <code>.cline.DiagnosticRange range = 2;</code>
   * @return The range.
   */
  bot.cline.proto.DiagnosticRange getRange();
  /**
   * <code>.cline.DiagnosticRange range = 2;</code>
   */
  bot.cline.proto.DiagnosticRangeOrBuilder getRangeOrBuilder();

  /**
   * <code>.cline.DiagnosticSeverity severity = 3;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.cline.DiagnosticSeverity severity = 3;</code>
   * @return The severity.
   */
  bot.cline.proto.DiagnosticSeverity getSeverity();

  /**
   * <code>optional string source = 4;</code>
   * @return Whether the source field is set.
   */
  boolean hasSource();
  /**
   * <code>optional string source = 4;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 4;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();
}
