// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface DiagnosticRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.DiagnosticRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cline.DiagnosticPosition start = 1;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>.cline.DiagnosticPosition start = 1;</code>
   * @return The start.
   */
  bot.cline.proto.DiagnosticPosition getStart();
  /**
   * <code>.cline.DiagnosticPosition start = 1;</code>
   */
  bot.cline.proto.DiagnosticPositionOrBuilder getStartOrBuilder();

  /**
   * <code>.cline.DiagnosticPosition end = 2;</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <code>.cline.DiagnosticPosition end = 2;</code>
   * @return The end.
   */
  bot.cline.proto.DiagnosticPosition getEnd();
  /**
   * <code>.cline.DiagnosticPosition end = 2;</code>
   */
  bot.cline.proto.DiagnosticPositionOrBuilder getEndOrBuilder();
}
