// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface FileDiagnosticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.FileDiagnostics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <code>repeated .cline.Diagnostic diagnostics = 2;</code>
   */
  java.util.List<bot.cline.proto.Diagnostic> 
      getDiagnosticsList();
  /**
   * <code>repeated .cline.Diagnostic diagnostics = 2;</code>
   */
  bot.cline.proto.Diagnostic getDiagnostics(int index);
  /**
   * <code>repeated .cline.Diagnostic diagnostics = 2;</code>
   */
  int getDiagnosticsCount();
  /**
   * <code>repeated .cline.Diagnostic diagnostics = 2;</code>
   */
  java.util.List<? extends bot.cline.proto.DiagnosticOrBuilder> 
      getDiagnosticsOrBuilderList();
  /**
   * <code>repeated .cline.Diagnostic diagnostics = 2;</code>
   */
  bot.cline.proto.DiagnosticOrBuilder getDiagnosticsOrBuilder(
      int index);
}
