// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface Int64OrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.Int64)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
