// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface StringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.String)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
