// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cline/common.proto

package bot.cline.proto;

public interface StringArraysOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cline.StringArrays)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string values1 = 1;</code>
   * @return A list containing the values1.
   */
  java.util.List<java.lang.String>
      getValues1List();
  /**
   * <code>repeated string values1 = 1;</code>
   * @return The count of values1.
   */
  int getValues1Count();
  /**
   * <code>repeated string values1 = 1;</code>
   * @param index The index of the element to return.
   * @return The values1 at the given index.
   */
  java.lang.String getValues1(int index);
  /**
   * <code>repeated string values1 = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the values1 at the given index.
   */
  com.google.protobuf.ByteString
      getValues1Bytes(int index);

  /**
   * <code>repeated string values2 = 2;</code>
   * @return A list containing the values2.
   */
  java.util.List<java.lang.String>
      getValues2List();
  /**
   * <code>repeated string values2 = 2;</code>
   * @return The count of values2.
   */
  int getValues2Count();
  /**
   * <code>repeated string values2 = 2;</code>
   * @param index The index of the element to return.
   * @return The values2 at the given index.
   */
  java.lang.String getValues2(int index);
  /**
   * <code>repeated string values2 = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the values2 at the given index.
   */
  com.google.protobuf.ByteString
      getValues2Bytes(int index);
}
